routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('cliente', 'App\Http\Controllers\ClienteController');
Route::resource('eventos', 'App\Http\Controllers\EventoController');
Route::resource('/catalogos', 'App\Http\Controllers\CatalogoController');
Route::resource('/extras', 'App\Http\Controllers\ExtrasController');

app/Models/evento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class evento extends Model
{
    use HasFactory;
}

app/Http/Controllers/EventoController.php
<?php

namespace App\Http\Controllers;

use App\Models\catalogo;
use App\Models\cobro;
use App\Models\direccion;
use App\Models\evento;
use App\Models\tipoPago;
use Illuminate\Http\Request;

class EventoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $eventos = evento::all();
        return view('eventos.index', compact('eventos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $direccion = direccion::all();
        $catalogo = catalogo::all();
        $cobro = cobro::all();
        $pago = tipoPago::all();
        return view('eventos.create', compact('direccion', 'catalogo', 'cobro', 'pago'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreeventoRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $eventos = new evento();

        $eventos->nombre = $request->get('nombre');
        $eventos->fecha = $request->get('fecha');
        $eventos->direccion_id = $request->get('direccion_id');
        $eventos->catalogo_id = $request->get('catalogo_id');
        $eventos->tipo_cobro_id = $request->get('tipo_cobro_id');
        $eventos->tipo_pago_id = $request->get('tipo_pago_id');

        $eventos->save();
        
        return redirect('/eventos');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\evento  $evento
     * @return \Illuminate\Http\Response
     */
    public function show(evento $evento)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\evento  $evento
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $eventos = evento::find($id);
        $direccion = direccion::all();
        $catalogo = catalogo::all();
        $cobro = cobro::all();
        $pago = tipoPago::all();
        return view('eventos.edit', compact('eventos', $eventos, 'direccion', $direccion, 'catalogo',  $catalogo, 'cobro', $cobro, 'pago', $pago));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  use Illuminate\Http\Request; $request
     * @param  \App\Models\evento  $evento
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $eventos = evento::find($id);

        $eventos->nombre = $request->get('nombre');
        $eventos->fecha = $request->get('fecha');
        $eventos->direccion_id = $request->get('direccion_id');
        $eventos->catalogo_id = $request->get('catalogo_id');
        $eventos->tipo_cobro_id = $request->get('tipo_cobro_id');
        $eventos->tipo_pago_id = $request->get('tipo_pago_id');

        $eventos->save();
        
        return redirect('/eventos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\evento  $evento
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $evento = evento::find($id);
        $evento->delete();
        return redirect('/eventos');
    }
}

resources/views/eventos/catalogo.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8">
               <div class="py-3">
                   <div class="px-8">
                   <h1>Creacion de catalogos</h1>
                    <form action="/catalogos" method="post">
                        @csrf
                        <div class="py-5 text-center row g-3">
                        <div class="form-group col-sm-6">
                            <label for="Nombre" class="form-label">Nombre del catalogo</label>
                            <input type="text" class="form-control" name="nombre">
                        </div>
                        <div class="input-group col-sm-6">
                <span class="input-group-text">Descripcion</span>
                <textarea class="form-control" name="descripcion" aria-label="With textarea"></textarea>
                         </div>
                         <div class="form-group">
                                <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
                                <div class="input-group">
                                <div class="input-group-addon">$</div>
                                <input type="number" name="costos" class="form-control" id="exampleInputAmount" placeholder="Amount">
                                </div>
                            </div>
                         <div class="container">
                <div class="btn-group " role="group" aria-label="Basic outlined example">
                <button type="submit" class="btn btn-outline-primary">GUARDAR</button>
                </div>
              </div>
                        </div>
                    </form>
                   </div>
               </div>
               <table class="table table-dark table-striped mt-4">
                   <thead class="thead-dark">
                       <h2>catalogos disponibles</h2>
                       <tr>
                           <th>#</th>
                           <th>Nombre</th>
                           <th>Descripcion</th>
                           <th>Precio</th>
                           <th scope="col">acciones</th>
                       </tr>
                   </thead>
                   <tbody>
                       @foreach($catalogos as $key)
                       <tr>
                       <td>{{$key->id}}</td>
                        <td>{{$key->nombre}}</td>
                        <td>{{$key->descripcion}}</td>
                        <td>{{$key->costos}}</td>
                        <td>
                            <form action="{{ route('catalogos.destroy',$key->id) }}" method="POST">      
              @csrf
              @method('DELETE')
          <button type="submit" class="btn btn-danger">Delete</button>
         </form>      </td>
                       </tr>
                       @endforeach
                   </tbody>
               </table>
               <a href="/" class="btn btn-primary col-sm-2" >REGRESAR</a>
        </div>
    </div>
</div>
@endsection

resources/views/eventos/create.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Interfaz</title>
  </head>
  <body>
    <div class="container">
      <div class="py-5 text-center">
          <h4 class="mb-3 fs-2">Registro Cliente</h4>
          <form method="post" action="/eventos">
              @csrf
            <div class="row g-3">
              <div class="col-sm-6">
                <label for="firstName" class="form-label">nombre del evento</label>
                <input type="text" class="form-control" name="nombre" required>
              </div>

              <div class="col-sm-6">
                <label for="lastName" class="form-label">fecha</label>
                <input type="date" class="form-control" name="fecha" required>
              </div>


              <div class="col-md-4">
                <label for="country" class="form-label">Direccion</label>
                <select class="form-select" name="direccion_id" required>
                  <option value="">...</option>
                  @foreach ($direccion as $key)
                  <option value="{{$key->id}}">{{$key->direccion}}</option>
                  @endforeach
                </select>
              </div>
  
              <div class="col-md-4">
                <label for="state" class="form-label">catalogo</label>
                <select class="form-select" name="catalogo_id" required>
                  <option value="">...</option>
                  @foreach ($catalogo as $key)
                  <option value="{{$key->id}}">{{$key->nombre}}</option>
                  @endforeach
                </select>
              </div>

              <div class="col-md-4">
                <label for="country" class="form-label">Cobro</label>
                <select class="form-select" name="tipo_cobro_id" required>
                  <option value="">...</option>
                  @foreach ($cobro as $key)
                  <option value="{{$key->id}}">{{$key->tipo_cobro}}</option>
                  @endforeach
                </select>
              </div>

              
              <div class="col-md-4">
                <label for="country" class="form-label">Tipo de pago</label>
                <select class="form-select" name="tipo_pago_id" required>
                  <option value="">...</option>
                  @foreach ($pago as $key)
                  <option value="{{$key->id}}">{{$key->tipo_pago}}</option>
                  @endforeach
                </select>
              </div>


              <div class="container">
                <div class="btn-group " role="group" aria-label="Basic outlined example">
                <button type="submit" class="btn btn-outline-primary">GUARDAR</button>
                </div>
              </div>

          </div>    
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/eventos/edit.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Interfaz</title>
  </head>
  <body>
    <div class="container">
      <div class="py-5 text-center">
          <h4 class="mb-3 fs-2">Registro Cliente</h4>
          <form method="post" action="/eventos/{{$eventos->id}}">
              @csrf
              @method('PUT')
            <div class="row g-3">
              <div class="col-sm-6">
                <label for="firstName" class="form-label">nombre del evento</label>
                <input type="text" class="form-control" name="nombre"value="{{$eventos->nombre}}" required>
              </div>

              <div class="col-sm-6">
                <label for="lastName" class="form-label">fecha</label>
                <input type="date" class="form-control" name="fecha" value="{{$eventos->fecha}}" required>
              </div>


              <div class="col-md-4">
                <label for="country" class="form-label">Direccion</label>
                <select class="form-select" name="direccion_id" required>
                  <option value="">...</option>
                  @foreach ($direccion as $key)
                  <option value="{{$key->id}}">{{$key->direccion}}</option>
                  @endforeach
                </select>
              </div>
  
              <div class="col-md-4">
                <label for="state" class="form-label">catalogo</label>
                <select class="form-select" name="catalogo_id" required>
                  <option value="">...</option>
                  @foreach ($catalogo as $key)
                  <option value="{{$key->id}}">{{$key->nombre}}</option>
                  @endforeach
                </select>
              </div>

              <div class="col-md-4">
                <label for="country" class="form-label">Cobro</label>
                <select class="form-select" name="tipo_cobro_id" required>
                  <option value="">...</option>
                  @foreach ($cobro as $key)
                  <option value="{{$key->id}}">{{$key->tipo_cobro}}</option>
                  @endforeach
                </select>
              </div>

              
              <div class="col-md-4">
                <label for="country" class="form-label">Tipo de pago</label>
                <select class="form-select" name="tipo_pago_id" required>
                  <option value="">...</option>
                  @foreach ($pago as $key)
                  <option value="{{$key->id}}">{{$key->tipo_pago}}</option>
                  @endforeach
                </select>
              </div>


              <div class="container">
                <div class="btn-group " role="group" aria-label="Basic outlined example">
                <button type="submit" class="btn btn-outline-primary">GUARDAR</button>
                </div>
              </div>

          </div>    
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/eventos/extras.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8">
               <div class="py-3">
                   <div class="px-8">
                   <h1>Añadidr contenido extra</h1>
                    <form action="/extras" method="post">
                        @csrf
                        <div class="py-5 text-center row g-3">
                        <div class="form-group col-sm-6">
                            <label for="Nombre" class="form-label">Nombre del catalogo</label>
                            <input type="text" class="form-control" name="nombre">
                        </div>
                        <div class="input-group col-sm-6">
                <span class="input-group-text">Descripcion</span>
                <textarea class="form-control" name="descripcion" aria-label="With textarea"></textarea>
                         </div>
                         <div class="form-group">
                                <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
                                <div class="input-group">
                                <div class="input-group-addon">$</div>
                                <input type="number" name="costos" class="form-control" id="exampleInputAmount" placeholder="Amount">
                                </div>
                            </div>
                         <div class="container">
                <div class="btn-group " role="group" aria-label="Basic outlined example">
                <button type="submit" class="btn btn-outline-primary">GUARDAR</button>
                </div>
              </div>
                        </div>
                    </form>
                   </div>
               </div>
               <table class="table table-dark table-striped mt-4">
                   <thead class="thead-dark">
                       <h2>Adiciones disponibles</h2>
                       <tr>
                           <th>#</th>
                           <th>Nombre</th>
                           <th>Descripcion</th>
                           <th>Precio</th>
                           <th scope="col">acciones</th>
                       </tr>
                   </thead>
                   <tbody>
                       @foreach($extras as $key)
                       <tr>
                       <td>{{$key->id}}</td>
                        <td>{{$key->nombre}}</td>
                        <td>{{$key->descripcion}}</td>
                        <td>{{$key->costos}}</td>
                        <td>
                            <form action="{{ route('extras.destroy',$key->id) }}" method="POST">      
              @csrf
              @method('DELETE')
          <button type="submit" class="btn btn-danger">Delete</button>
         </form>      </td>
                       </tr>
                       @endforeach
                   </tbody>
               </table>
               <a href="/" class="btn btn-primary col-sm-2" >REGRESAR</a>
        </div>
    </div>
</div>
@endsection

resources/views/eventos/index.blade.php
@extends('layouts.app')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="col-sm-12">
            <div class="py-3">
                <div class="px-4">
                    <div class="row justify-center">
                    <h1>listado de eventos</h1>
                    <a href="eventos/create" class="btn btn-primary col-sm-2" >CREAR</a>
<table class="table table-dark table-striped mt-4">
<thead class="thead-dark">
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">nombre</th>
                            <th scope="col">fecha</th>
                            <th scope="col">direccion</th>
                            <th scope="col">catalogo</th>
                            <th scope="col">tipo de pago</th>
                            <th scope="col">acciones</th>
                            </tr>
                        </thead>
  <tbody>    
                      @foreach ($eventos as $key)
                        <tr>
                            <td>{{$key->id}}</td>
                            <td>{{$key->nombre}}</td>
                            <td>{{$key->fecha}}</td>
                            <td>{{$key->direccion_id}}</td>
                            <td>{{$key->catalogo_id}}</td>
                            <td>{{$key->tipo_pago_id}}</td>

        <td>
         <form action="{{ route('eventos.destroy',$key->id) }}" method="POST">
          <a href="/eventos/{{$key->id}}/edit" class="btn btn-info">Editar</a>         
              @csrf
              @method('DELETE')
          <button type="submit" class="btn btn-danger">Delete</button>
         </form>          
        </td>        
    </tr>
    @endforeach
  </tbody>
</table>
                </div>
            </div>
            <a href="/" class="btn btn-primary col-sm-2" >REGRESAR</a>
        </div>
    </div>
</body>
</html>