routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('cliente', 'App\Http\Controllers\ClienteController');
Route::resource('eventos', 'App\Http\Controllers\EventoController');
Route::resource('/catalogos', 'App\Http\Controllers\CatalogoController');
Route::resource('/extras', 'App\Http\Controllers\ExtrasController');

app/Models/cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class cliente extends Model
{
    use HasFactory;



    public function estado()
    {
        return $this->hasOne(estado::class,);
    }
    
    public function municipio()
    {
        return $this->hasOne(municipio::class);
    }
    
    public function parroquia()
    {
        return $this->hasOne(parroquia::class);
    }
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Models\cliente;
use App\Models\estado;
use App\Models\municipio;
use App\Models\parroquia;
use Illuminate\Http\Request;


class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clientes = cliente::all();
        return view('cliente.index', compact('clientes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $estados = estado::all();
        $municipios = municipio::all();
        $parroquias = parroquia::all();
        return view('cliente.create', compact('estados', 'municipios', 'parroquias'));
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Request    $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $clientes = new cliente();

        $clientes->nombre = $request->get('nombre');
        $clientes->apellido = $request->get('apellido');
        $clientes->cedula = $request->get('cedula');
        $clientes->direccion = $request->get('direccion');
        $clientes->telefono = $request->get('telefono');
        $clientes->email = $request->get('email');
        $clientes->estados_id = $request->get('estados_id');
        $clientes->municipios_id = $request->get('municipios_id');
        $clientes->parroquias_id = $request->get('parroquias_id');

        $clientes->save();
        
        return redirect('/cliente');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function show(cliente $cliente)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cliente = cliente::findOrFail($id);
        $estado = estado::all();
        $municipio = municipio::all();
        $parroquia = parroquia::all();
        return view('cliente.edit', compact('cliente', $cliente, 'estado', $estado, 'municipio',  $municipio, 'parroquia', $parroquia ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Request  $request
     * @param  \App\Models\cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cliente = cliente::find($id);

        $cliente->nombre = $request->get('nombre');
        $cliente->apellido = $request->get('apellido');
        $cliente->cedula = $request->get('cedula');
        $cliente->direccion = $request->get('direccion');
        $cliente->telefono = $request->get('telefono');
        $cliente->email = $request->get('email');
        $cliente->estados_id = $request->get('estados_id');
        $cliente->municipios_id = $request->get('municipios_id');
        $cliente->parroquias_id = $request->get('parroquias_id');

        $cliente->save();
        
        return redirect('/cliente');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cliente = cliente::find($id);
        $cliente->delete();
        return redirect('/cliente');
    }
}

resources/views/cliente/create.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Interfaz</title>
  </head>
  <body>
    <div class="container">
      <div class="py-5 text-center">
          <h4 class="mb-3 fs-2">Registro Cliente</h4>
          <form method="post" action="/cliente">
              @csrf
            <div class="row g-3">
              <div class="col-sm-6">
                <label for="firstName" class="form-label">Nombres</label>
                <input type="text" class="form-control" name="nombre" required>
              </div>

              <div class="col-sm-6">
                <label for="lastName" class="form-label">Apellidos</label>
                <input type="text" class="form-control" name="apellido" required>
              </div>

              <div class="col-sm-6">
                <label for="lastName" class="form-label">Numero de Identidad</label>
                <input type="text" class="form-control" name="cedula" required>
              </div>

              <div class="col-sm-6">
                <label for="firstName" class="form-label">Correo Electronico</label>
                <input type="email" class="form-control" name="email" value="" required>
              </div>
              <div class="input-group">
                <span class="input-group-text">Nro Telefono</span>
                <input type="text" name="telefono" class="form-control">
              </div>

              <div class="col-md-4">
                <label for="country" class="form-label">Estado</label>
                <select class="form-select" name="estados_id" required>
                  <option value="">...</option>
                  @foreach ($estados as $key)
                  <option value="{{$key->id}}">{{$key->estado}}</option>
                  @endforeach
                </select>
              </div>
  
              <div class="col-md-4">
                <label for="state" class="form-label">Municipio</label>
                <select class="form-select" name="municipios_id" required>
                  <option value="">...</option>
                  @foreach ($municipios as $key)
                  <option value="{{$key->id}}">{{$key->municipio}}</option>
                  @endforeach
                </select>
              </div>

              <div class="col-md-4">
                <label for="country" class="form-label">Parroquia</label>
                <select class="form-select" name="parroquias_id" required>
                  <option value="">...</option>
                  @foreach ($parroquias as $key)
                  <option value="{{$key->id}}">{{$key->parroquia}}</option>
                  @endforeach
                </select>
              </div>

              <div class="input-group">
                <span class="input-group-text">Direccion</span>
                <textarea class="form-control" name="direccion" aria-label="With textarea"></textarea>
              </div>

              <div class="container">
                <div class="btn-group " role="group" aria-label="Basic outlined example">
                <button type="submit" class="btn btn-outline-primary">GUARDAR</button>
                </div>
              </div>

          </div>    
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/cliente/edit.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Interfaz</title>
  </head>
  <body>
    <div class="container">
      <div class="py-5 text-center">
          <h4 class="mb-3 fs-2">Registro Cliente</h4>
          <form action="/cliente/{{$cliente->id}}" method="POST">
              @csrf
              @method('PUT')
            <div class="row g-3">
              <div class="col-sm-6">
                <label for="firstName" class="form-label">Nombres</label>
                <input type="text" class="form-control" name="nombre" value="{{$cliente->nombre}}" required>
              </div>

              <div class="col-sm-6">
                <label for="lastName" class="form-label">Apellidos</label>
                <input type="text" class="form-control" name="apellido" value="{{$cliente->apellido}}" required>
              </div>

              <div class="col-sm-6">
                <label for="lastName" class="form-label">Numero de Identidad</label>
                <input type="text" class="form-control" name="cedula" value="{{$cliente->cedula}}" required>
              </div>

              <div class="col-sm-6">
                <label for="firstName" class="form-label">Correo Electronico</label>
                <input type="email" class="form-control" name="email"  value="{{$cliente->email}}"  required>
              </div>
              <div class="input-group">
                <span class="input-group-text">Nro Telefono</span>
                <input type="text" name="telefono" value="{{$cliente->telefono}}"  class="form-control">
              </div>

              <div class="col-md-4">
                <label for="country" class="form-label">Estado</label>
                <select class="form-select" name="estados_id" required>
                  <option value="">...</option>
                  @foreach ($estado as $key)
                  <option value="{{$key->id}}">{{$key->estado}}</option>
                  @endforeach
                </select>
              </div>
  
              <div class="col-md-4">
                <label for="state" class="form-label">Municipio</label>
                <select class="form-select" name="municipios_id" required>
                  <option value="">...</option>
                  @foreach ($municipio as $key)
                  <option value="{{$key->id}}">{{$key->municipio}}</option>
                  @endforeach
                </select>
              </div>

              <div class="col-md-4">
                <label for="country" class="form-label">Parroquia</label>
                <select class="form-select" name="parroquias_id" required>
                  <option value="">...</option>
                  @foreach ($parroquia as $key)
                  <option value="{{$key->id}}">{{$key->parroquia}}</option>
                  @endforeach
                </select>
              </div>

              <div class="input-group">
                <span class="input-group-text">Direccion</span>
                <textarea class="form-control" name="direccion" value="{{$cliente->direccion}}" aria-label="With textarea"></textarea>
              </div>

              <div class="container">
                <div class="btn-group " role="group" aria-label="Basic outlined example">
                <button type="submit" class="btn btn-outline-primary">GUARDAR</button>
                </div>
              </div>

          </div>    
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/cliente/index.blade.php
@extends('layouts.app')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="col-sm-12">
            <div class="py-3">
                <div class="px-4">
                    <div class="row justify-center">
                    <h1>listado de clientes</h1>
                    <a href="cliente/create" class="btn btn-primary col-sm-2" >CREAR</a>


<table class="table table-dark table-striped mt-4">
<thead class="thead-dark">
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">nombre</th>
                            <th scope="col">apellido</th>
                            <th scope="col">cedula</th>
                            <th scope="col">direccion</th>
                            <th scope="col">telefono</th>
                            <th scope="col">email</th>
                            <th scope="col">cod_estado</th>
                            <th scope="col">cod_municipio</th>
                            <th scope="col">cod_parroquuia</th>
                            <th scope="col">acciones</th>
                            </tr>
                        </thead>
  <tbody>    
  @foreach ($clientes as $key)
                        <tr>
                            <td>{{$key->id}}</td>
                            <td>{{$key->nombre}}</td>
                            <td>{{$key->apellido}}</td>
                            <td>{{$key->cedula}}</td>
                            <td>{{$key->direccion}}</td>
                            <td>{{$key->telefono}}</td>
                            <td>{{$key->email}}</td>
                            <td>{{$key->estados_id}}</td>
                            <td>{{$key->municipios_id}}</td>
                            <td>{{$key->parroquias_id}}</td>
        <td>
         <form action="{{ route('cliente.destroy',$key->id) }}" method="POST">
          <a href="/cliente/{{$key->id}}/edit" class="btn btn-info">Editar</a>         
              @csrf
              @method('DELETE')
          <button type="submit" class="btn btn-danger">Delete</button>
         </form>          
        </td>        
    </tr>
    @endforeach
  </tbody>
</table>
<a href="/" class="btn btn-primary col-sm-2" >REGRESAR</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>